### ISSUE TITLE
Custom build system reasoning

### ISSUE THREAD

**Issue by IK-Adrian** [awslabs/aws-greengrass-labs-certificate-rotator#59]
Is there any reason for the custom Python script used as the build system instead of the GDK-integrated ZIP build system?

**Comment by gregbreen** [comment]
Hi. It's because the ZIP build system didn't offer good control over what to exclude from the ZIP. That seems to have been improved since this repo was published: https://github.com/aws-greengrass/aws-greengrass-gdk-cli/releases/tag/v1.5.0
