### ISSUE TITLE
Certificate Rotator Component Deployment Stuck in “In Progress” State

### ISSUE THREAD

**Issue by JoonasEronen** [awslabs/aws-greengrass-labs-certificate-rotator#66]
I am trying to deploy the AWS Greengrass Labs Certificate Rotator component on my device, but the deployment gets stuck in the “in progress” state. I have followed the Certificate Rotator instructions and performed all steps.

What can usually cause this and what should be checked next?

**Comment by gregbreen** [comment]
Hi @JoonasEronen . Please check the component log at `/greengrass/v2/logs/aws.greengrass.labs.CertificateRotator.log` on the device (if Greengrass is installed in the default location).
